# database
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/minesweeper?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false}
    hikari:
      jdbc-url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/minesweeper?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false}
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD:password}
  flyway:
    enabled: true
    locations: classpath:/db/migrations
